#!/bin/bash

set -e

if [[ -n $1 ]]; then
  DEPLOY_ENV=$1
fi

if [[ "${BUILDKITE_PULL_REQUEST}" != "false" ]]; then
  echo "Not deploying because this is a pull request"
  exit 0
fi

if hash buildkite-agent 2>/dev/null; then
  DOCKER_IMAGE=$(buildkite-agent meta-data get docker-image)
fi

if [[ -z $DOCKER_IMAGE ]]; then
  echo "DOCKER_IMAGE is required (repo/of/image:version)"
  exit 1
fi

IMAGE_TAG=$(echo $DOCKER_IMAGE | awk -F: '{print $2}')

echo '--- updating fleet service template'
perl -p -i -e "s/^Environment=VERSION=.+$/Environment=VERSION=${IMAGE_TAG}/" synapse-balancer@.service
perl -p -i -e "s/^Environment=DEPLOY_ENV=.*$/Environment=DEPLOY_ENV=${DEPLOY_ENV}/" synapse-balancer@.service

fleetctl destroy synapse-balancer@.service || true # may not exist
fleetctl submit synapse-balancer@.service

echo '--- (re-)starting fleet service instances'
NODE_COUNT=$(curl -s http://${DEPLOY_ENV}.democracy.works:8500/v1/catalog/nodes | jq length)
for i in $(seq 1 ${NODE_COUNT}); do
  fleetctl stop synapse-balancer@$i
  fleetctl destroy synapse-balancer@$i || true # may not exist
  fleetctl start synapse-balancer@$i
  # TODO: Use consul to see if synapse-balancer@$i is healthy yet before moving on
done
