#!/bin/bash

set -ex

DEPLOY_USER=deploy

function usage() {
  echo -e "Usage:\n\ndeploy docker_image\n\nEx: deploy quay.io/democracyworks/buildbox-docker:latest"
}

echo '--- retrieving repo and tag'
if [[ -z $DOCKER_IMAGE ]]; then
  if [[ ! -z $1 ]]; then
    DOCKER_IMAGE=$1
  elif hash buildbox-artifact 2>/dev/null; then
    buildbox-artifact download docker_image .
    DOCKER_IMAGE=$(<docker_image)
  fi
fi

if [[ -z $DOCKER_IMAGE ]]; then
  usage
  exit 1
fi

deploy_hosts=(docker1-int.turbovote.org docker2-int.turbovote.org)

for host in ${deploy_hosts[@]}; do
  echo "--- deploying to $host"
  scp -o StrictHostKeyChecking=no $(dirname $0)/remote_deploy $DEPLOY_USER@$host:
  ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$host "DOCKER_IMAGE=$DOCKER_IMAGE ./remote_deploy"
done
